---
title: "Notes on Geomorphology and STZ development"
output: pdf_document
header-includes:
  - \usepackage{setspace}
  - \setlength{\headsep}{0cm}
---
\doublespacing

The effects of climate and extreme weather on plant survival and growth are mediated directly and indirectly by landforms, and indirectly by soil across a range of spatial scales (Giaccone et al. 2019, Moesland et al 2013, Swanson et al. 1988). 
Landforms directly influence climate to produce micro-climates such as cold pools and micro-rain shadows, resulting in variations in evapotranspiration and soil moisture availability gradients, even in relatively flat landscapes (Pastore et al. 2022, Minder et al. 2008). 
Topographic slope and aspect control the amount of incipient solar radiation generating local gradients in both soil temperature and soil moisture (Dearborn and Danby 2017).
Landform features and positions have also been shown to influence the amount of soil moisture, at various depths and across time, by altering the amount of overland, and subsurface, water flow leading to areas with either elevated or reduced soil moisture (McAuliffe 1994, Wondzell et al. 1996, Qui et al. 2001). 
Soil moisture has naturally also been shown to be influenced by the number of soil properties such as coarse fragments throughout the horizons (Katra et al. 2008), as well as physical texture (English et al. 2005, Fernandez-Illescas et al. 2001, Singh et al. 1998), and chemical properties (e.g., carbonates and soil organic carbon) (Duniway et al. 2010, Rawls et al. 2003).
Collectively, these factors can lead to a decoupling between the resolution of climate variables generated by climatological spatial modelling and the responses of plant populations to evapotranspirative demands (Ackerly et al. 2020, Potter et al. 2013, Lenoir et al. 2016).  

Effectively, the decoupling between climate and soil moisture may result in idiosyncratic results in common garden studies, where source populations may be adapted to drier (e.g., coarse soils, south-facing aspects, ridgelines) or wetter conditions (e.g., fine soils, northern aspects, footslopes) than climate alone would indicate. 
This may affect both fitting regression models to the canonical correlation analysis (CCA) axes of traits (such as phenology dates and productivity) measured in common gardens -which form the basis for seed transfer zone groups- and the prediction of these models into environmental and geographic space, and hence the subsequent partitioning of areas into seed transfer zones. 
A similar cost could be associated with seed transfer zone models based on correlative ecological niche models and climate matching (for example, Crow et al. 2018, Shyrock et al. 2017), except that the original models would fit directly to a binary (or somatic growth) response without the possibility of a common garden to mitigate any effects; however, given the potential for larger samples, this effect may be ameliorated.  

The direct effects of topography on climate are a well-known phenomenon, and various approaches for downscaling gridded climate data from moderate (e.g. ~4km, ~1km, ~800m) to finer resolutions (e.g. 30m) have been developed and shown to better capture local climatology (Potter et al. 2013, Wang et al. 2016). 
The use of these downscaled data sets (e.g. ClimateNA) has already been implemented by the majority of researchers (for example, Johnson et al. 2017, St. Clair et al. 2013, Shyrock et al. 2017). 
Although these tools are more effective for modelling localized climates, they do not address the effects of geomorphology on precipitation that has reached the soil surface. 
However, recent advances in LiDAR have made the inclusion of moderate to high resolution landform attributes, such as topographic position, topographic wetness indices, aspect, slope, and terrain-derived derivatives, achievable with data products such as Geormopho90m (Amatulli et al. 2018; Amatulli et al. 2020) or can be readily calculated using a variety of geographic information systems (e.g., WhiteBoxTools). 
As covariates landform attributes may help explain responses between populations; for example, many populations from more arid regions may actually be located in refugial areas (e.g., northern facing toes of slope) where they are buffered from the realized microclimate. 

Moderate resolution soil data are available for a variety of physical and chemical components (for example SoilGrids), as well as soil moisture; however, in our experience, these data are less accurate than the aforementioned topographic data sets because of the disparity in the abilities of remote sensing approaches (Hengl et al. 2017, Vergopolan et al. 2021).
Gibson et al. 2019 used soil covariates from the SSURGO database and found variables which moderate soil moisture, such as soil organic carbon and percent clay, and were able to decrease variance in models relating common garden results to source populations. 
However, within their region of analysis, the climate-only models suggested three zones, and the climate + soil models generated eight zones, four of which collectively constituted less than 5%, relative to XX pSTZ (*REED has reached out to authors to get this product to run an intersection and join count*) for treating the same area (Bower et al. 2014). 
Hence, while utilization of geomorphological covariates may increase predictive abilities, they may also create more seed zones than are practical, especially small isolated patches within larger zones (Gibson et al. 2019; Shyrock, unpublished data) and their incorporation may require post-processing steps where STZs with very small total geographic coverage are removed from downstream applications, for example, by reassignment to their nearest neighbors; or if retained a raster of multi class classifications can help land managers determine if development of materials for these zones are warranted (see Benkendorf & Wieferich *in revision*). 

Note that, aside from 'extreme' or harsh soils such as (for example mine tailings, serpentine, gypsum, limestones, marine clays, and tuffs) evidence for adaption of plant populations to individual soil types appears to seldom be documented in the literature (Macel et al. 2007, Ellis & Ågren 2024, O'Dell & Rajakaruna), indicating that most populations for most species appear suitable for restoration sites of appropriate aridity levels. 
Notably, several experiments show that the abiotic soil environment alone does not show cases differences in fitness between ecotypes, in the absence of another stressor such as herbivory or drought (Dittmar & Schemske 2023, Dorey et al. 2024). 
And that for 'common' soil types the effect of micro-organisms have been shown to be more strong than abiotic effects (Sherrard & Maherali 2011), *SECTION XX*.
In restoration contexts, of five commonly used restoration species of Central European grasslands only one showed a weak adaption to acidic soils (relative to calcareous) (Rupprecht et al. 2021), and in an evaluation of eSTZs in the Great Basin USA no evidence of adaption to local soil types, or differing survival on different common garden soils were observed (Davidson & Germino 2020). 
Hence our recommendation for focusing on continuous landform and soil variables which affect soil moisture, rather than using soil classes, for research. 

## Restoration Action 

Restoration practitioners, when presented with multiple seed source options for a restoration and which have similar climate similarity to the site, have expressed interest in matching seed sources to site using additional criteria. 
Under certain scenarios, the use of ecological site descriptions (ESD's) will articulate the relationship between climate, geomorphology, and the response of vegetation to sites (Moseley et al. 2010). 
While there are many individual ESDs, in our experience, a small subset of them make up large proportions of geographic space in any given area (Benkendorf & Holsinger 2024). 
The use of ESDs will not only lead to a match between climate and geomorphology, but also foster the selection of seed lots where the focal species has been in a similar vegetation context to it's desired outcome (**SECTION XX**), i.e. the population will have been exposed to other species likely to recruit at the site, or to be seeded. 
However, the development of ESDs across Western North America has been a long process, and the status of their mapping is variable, and to date no gridded surfaces for them exist (Benkendorf & Holsinger 2024, Brown 2010). 
A possible solution has been the development of Ecological Site Groups (ESGs), which combine local expertise with geospatial modelling approaches, and have been developed for at least one large geographic domain (the Colorado Plateau) (Nauman et al. 2022). 
While ESGs do not offer the same thematic resolution as ESDs, they still reflect the interactions between climate and geomorphology, and may be used in the interim to express these relationships within seed transfer zones; further as they are developed computationally they can developed in a cost-effective manner (Nauman et al. 2022). 
For immediate use, practitioners may be able to combine data sets which classify landform positions, with continuous soil textural and physical properties (discussed above) to help inform the similarity between prospective seed sources and a restoration site; however these approach is more time intensive and will require extensive domain knowledge. 
Finally, combining multiple data sets, e.g. climate similarity and geomorphology, may result in more rather than less confusion when selecting plant materials without a clearly defined workflow for decision making. 

# Maternal mother effects stuff

An additional influence of soil conditions at the wildland seed collection site in common garden studies may be environmental maternal effects, which have been experimentally demonstrated to be related to abiotic soil conditions and drought stress (Bischoff & Müller-Schärer 2010, Vivas et al. 2020). 
Maternal plant phenotypes influence the seed mass of their progeny, which influences germination and the growth of young plants in a range of species, but appear most pronounced on progeny in low-nutrient or stressful environments (Bischoff & Müller-Schärer 2010, Schmid & Dolt 1994).
Beyond the direct maternal effect of seed mass, environmental maternal effects - a form of transgenerational phenotypic plasticity– have also been shown to influence the early stages of plant growth for some species investigated (Galloway 2005, Galloway & Etterson 2007, Vivas et al. 2020), but not others (Monty et al. 2009), **SECTION XX**. 
